version: "3.3"
services:
  spark-master:
    image: luuhungcuong/spark:v2.3.3
    hostname: spark-master
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080    
    environment:      
      - "SPARK_PUBLIC_DNS=192.168.0.162"
      - "SPARK_NODE_TYPE=MASTER"    
    deploy:
      placement:
        constraints: [node.role == manager]
  spark-worker:
    image: luuhungcuong/spark:v2.3.3
    depends_on:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081
    environment:      
      - "SPARK_PUBLIC_DNS=192.168.0.162"   
      - "SPARK_NODE_TYPE=SLAVE"         
      - "SPARK_MASTER_NOTE=spark-master"    
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8088:8080"    
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]